import 'package:flutter/material.dart';
import '../models/challenge.dart';

final List<Challenge> exclusiveChallenges = [
  const Challenge(
    id: 'pushup-foundation',
    title: '7-Day Push-up Foundation',
    description: 'Build your upper body strength one rep at a time.',
    icon: Icons.fitness_center_rounded,
    difficulty: ChallengeDifficulty.easy,
    tags: ['Strength', 'Upper Body', 'Chest'],
    duration: '7d',
    timePerDay: '20m',
    activeCount: 4,
    joinedCount: 6,
    isTrending: true,
    goalValue: 100,
    goalType: ChallengeGoalType.sets,
    targetMuscle: 'chest',
    eloReward: 30,
    steps: [
      'Log 100 total sets of chest exercises within 7 days.',
      'Maintain a consistent 20m training time per day.',
      'Variations like Incline Press, Pec Deck, or Push-ups count.',
      'Focus on slow, controlled eccentric reps to build the foundation.'
    ],
  ),
  const Challenge(
    id: 'solo-leveling',
    title: 'The Solo Leveling Challenge',
    description: 'A grueling daily regime to break your limits and reach the top.',
    difficulty: ChallengeDifficulty.hard,
    tags: ['Endurance', 'Full Body', 'Hard'],
    duration: '30d',
    timePerDay: '120m',
    activeCount: 6,
    joinedCount: 6,
    isTrending: true,
    goalValue: 30,
    goalType: ChallengeGoalType.sessions,
    eloReward: 120,
    steps: [
      'Complete 30 workout sessions in 30 days (1 per day).',
      'Each session must be at least 120 minutes long.',
      'All major muscle groups should be trained over the week.',
      'Warning: This regime is designed to test your limits. Listen to your body.'
    ],
  ),
  const Challenge(
    id: 'spartan-300',
    title: 'Spartan 300',
    description: '300 repetitions of high-intensity functional movements. Can you survive?',
    difficulty: ChallengeDifficulty.extreme,
    tags: ['Strength', 'Extreme', 'Full Body'],
    duration: '1d',
    timePerDay: '60m',
    activeCount: 2,
    joinedCount: 15,
    goalValue: 300,
    goalType: ChallengeGoalType.sets,
    eloReward: 250,
    steps: [
      'Complete 300 total sets of mixed exercises in a single day.',
      'Recommended: Deadlifts, Kettlebell Swings, Burpees, Pull-ups.',
      'Complete as fast as possible while maintaining form.',
      'Only for elite athletes with a high recovery score.'
    ],
  ),
  const Challenge(
    id: 'titan-chest',
    title: 'Titan Chest',
    description: 'Advanced hypertrophy routine for a massive, powerful chest development.',
    difficulty: ChallengeDifficulty.hard,
    tags: ['Hypertrophy', 'Advanced', 'Chest'],
    duration: '21d',
    timePerDay: '45m',
    activeCount: 3,
    joinedCount: 12,
    goalValue: 200,
    goalType: ChallengeGoalType.sets,
    targetMuscle: 'chest',
    eloReward: 100,
    steps: [
      'Log 200 chest sets over 21 days.',
      'Focus on heavy compound movements (Bench Press, Dips).',
      'Incorporate 2 recovery days per week to allow for growth.',
      'Aim for a progressive overload of 2.5kg per week.'
    ],
  ),
  const Challenge(
    id: 'mountain-leg-surge',
    title: 'Mountain Leg Surge',
    description: 'High volume leg training inspired by mountain climbers and elite cyclists.',
    difficulty: ChallengeDifficulty.hard,
    tags: ['Endurance', 'Hard', 'Legs'],
    duration: '30d',
    timePerDay: '40m',
    activeCount: 1,
    joinedCount: 8,
    goalValue: 150,
    goalType: ChallengeGoalType.sets,
    targetMuscle: 'quads',
    eloReward: 90,
    steps: [
      'Log 150 sets of leg exercises (Quads focus).',
      'Include Squats, Leg Press, and Lunges.',
      'At least 2 sessions per week should be high-intensity.',
      'Progressive increase of volume is required to stay active.'
    ],
  ),
  const Challenge(
    id: 'iron-core-mastery',
    title: 'Iron Core Mastery',
    description: 'Stabilize your foundation with daily core-focused strength drills.',
    difficulty: ChallengeDifficulty.medium,
    tags: ['Stability', 'Medium', 'Core'],
    duration: '14d',
    timePerDay: '15m',
    activeCount: 5,
    joinedCount: 22,
    goalValue: 100,
    goalType: ChallengeGoalType.sets,
    targetMuscle: 'core',
    eloReward: 50,
    steps: [
      'Log 100 sets of core-focused exercises.',
      'Planks, Leg Raises, and Hanging Crunches are recommended.',
      'Focus on isometric holds for minimum 45 seconds to count as a "set".',
      'Daily 15m routine is required for the duration.'
    ],
  ),
];
